spring:
  application:
    name: shopIt

  datasource:
    url: jdbc:postgresql://localhost:5432/shopIt
    username: postgres
    password: postgres
  jpa:
    show-sql: true

  jwt:
    secret: ${JWT_SECRET}
    accessTokenExpiration: 300
    refreshTokenExpiration: 604800

server:
  port: 8081
  servlet:
    context-path: /api
